import { ImageSourcePropType } from 'react-native';

const serviceLogoSources: Record<string, ImageSourcePropType> = {
  '1password': require('../assets/service-logos/1password.png'),
  adobe_creative_cloud: require('../assets/service-logos/adobe_creative_cloud.png'),
  adobe_lightroom: require('../assets/service-logos/adobe_lightroom.png'),
  adobe_premiere_pro: require('../assets/service-logos/adobe_premiere_pro.png'),
  ahrefs: require('../assets/service-logos/ahrefs.png'),
  amazon_music: require('../assets/service-logos/amazon_music.png'),
  amazon_prime: require('../assets/service-logos/amazon_prime.png'),
  amazon_prime_video: require('../assets/service-logos/amazon_prime_video.png'),
  apple_fitnessplus: require('../assets/service-logos/apple_fitnessplus.png'),
  apple_music: require('../assets/service-logos/apple_music.png'),
  apple_tvplus: require('../assets/service-logos/apple_tvplus.png'),
  artlist: require('../assets/service-logos/artlist.png'),
  bitwarden: require('../assets/service-logos/bitwarden.png'),
  bloomberg: require('../assets/service-logos/bloomberg.png'),
  brilliant: require('../assets/service-logos/brilliant.png'),
  buffer: require('../assets/service-logos/buffer.png'),
  calm: require('../assets/service-logos/calm.png'),
  canva: require('../assets/service-logos/canva.png'),
  capcut_pro: require('../assets/service-logos/capcut_pro.png'),
  chatgpt_plus: require('../assets/service-logos/chatgpt_plus.png'),
  claude_pro: require('../assets/service-logos/claude_pro.png'),
  coursera_plus: require('../assets/service-logos/coursera_plus.png'),
  crunchyroll: require('../assets/service-logos/crunchyroll.png'),
  curiosity_stream: require('../assets/service-logos/curiosity_stream.png'),
  discord_nitro: require('../assets/service-logos/discord_nitro.png'),
  discoveryplus: require('../assets/service-logos/discoveryplus.png'),
  disneyplus: require('../assets/service-logos/disneyplus.png'),
  dropbox: require('../assets/service-logos/dropbox.png'),
  duolingo_plus: require('../assets/service-logos/duolingo_plus.png'),
  ea_play: require('../assets/service-logos/ea_play.png'),
  envato_elements: require('../assets/service-logos/envato_elements.png'),
  epidemic_sound: require('../assets/service-logos/epidemic_sound.png'),
  evernote: require('../assets/service-logos/evernote.png'),
  expressvpn: require('../assets/service-logos/expressvpn.png'),
  figma: require('../assets/service-logos/figma.png'),
  final_cut_pro: require('../assets/service-logos/final_cut_pro.png'),
  github_copilot: require('../assets/service-logos/github_copilot.png'),
  google_one: require('../assets/service-logos/google_one.png'),
  google_workspace: require('../assets/service-logos/google_workspace.png'),
  grammarly: require('../assets/service-logos/grammarly.png'),
  hbo_max: require('../assets/service-logos/hbo_max.png'),
  headspace: require('../assets/service-logos/headspace.png'),
  hootsuite: require('../assets/service-logos/hootsuite.png'),
  hulu: require('../assets/service-logos/hulu.png'),
  icloudplus: require('../assets/service-logos/icloudplus.png'),
  kick_subscription: require('../assets/service-logos/kick_subscription.png'),
  lastpass: require('../assets/service-logos/lastpass.png'),
  later: require('../assets/service-logos/later.png'),
  masterclass: require('../assets/service-logos/masterclass.png'),
  medium_membership: require('../assets/service-logos/medium_membership.png'),
  mega: require('../assets/service-logos/mega.png'),
  microsoft_365: require('../assets/service-logos/microsoft_365.png'),
  midjourney: require('../assets/service-logos/midjourney.png'),
  moz: require('../assets/service-logos/moz.png'),
  mubi: require('../assets/service-logos/mubi.png'),
  myfitnesspal: require('../assets/service-logos/myfitnesspal.png'),
  netflix: require('../assets/service-logos/netflix.png'),
  nintendo_switch_online: require('../assets/service-logos/nintendo_switch_online.png'),
  noom: require('../assets/service-logos/noom.png'),
  nordvpn: require('../assets/service-logos/nordvpn.png'),
  notion: require('../assets/service-logos/notion.png'),
  paramountplus: require('../assets/service-logos/paramountplus.png'),
  pcloud: require('../assets/service-logos/pcloud.png'),
  peacock: require('../assets/service-logos/peacock.png'),
  perplexity_pro: require('../assets/service-logos/perplexity_pro.png'),
  playstation_plus: require('../assets/service-logos/playstation_plus.png'),
  proton_mail: require('../assets/service-logos/proton_mail.png'),
  proton_vpn: require('../assets/service-logos/proton_vpn.png'),
  quickbooks: require('../assets/service-logos/quickbooks.png'),
  rosetta_stone: require('../assets/service-logos/rosetta_stone.png'),
  runway: require('../assets/service-logos/runway.png'),
  seeking_alpha: require('../assets/service-logos/seeking_alpha.png'),
  semrush: require('../assets/service-logos/semrush.png'),
  shopify: require('../assets/service-logos/shopify.png'),
  skillshare: require('../assets/service-logos/skillshare.png'),
  slack: require('../assets/service-logos/slack.png'),
  soundcloud_go: require('../assets/service-logos/soundcloud_go.png'),
  spotify: require('../assets/service-logos/spotify.png'),
  squarespace: require('../assets/service-logos/squarespace.png'),
  storyblocks: require('../assets/service-logos/storyblocks.png'),
  strava: require('../assets/service-logos/strava.png'),
  substack: require('../assets/service-logos/substack.png'),
  surfshark: require('../assets/service-logos/surfshark.png'),
  telegram_premium: require('../assets/service-logos/telegram_premium.png'),
  the_economist: require('../assets/service-logos/the_economist.png'),
  the_new_york_times: require('../assets/service-logos/the_new_york_times.png'),
  the_washington_post: require('../assets/service-logos/the_washington_post.png'),
  tidal: require('../assets/service-logos/tidal.png'),
  todoist: require('../assets/service-logos/todoist.png'),
  tradingview: require('../assets/service-logos/tradingview.png'),
  twitch_turbo: require('../assets/service-logos/twitch_turbo.png'),
  ubisoftplus: require('../assets/service-logos/ubisoftplus.png'),
  udemy: require('../assets/service-logos/udemy.png'),
  webflow: require('../assets/service-logos/webflow.png'),
  wix: require('../assets/service-logos/wix.png'),
  xbox_game_pass: require('../assets/service-logos/xbox_game_pass.png'),
  ynab: require('../assets/service-logos/ynab.png'),
  youtube_music: require('../assets/service-logos/youtube_music.png'),
  youtube_premium: require('../assets/service-logos/youtube_premium.png'),
  zoom: require('../assets/service-logos/zoom.png'),
};

export function getServiceLogoSource(serviceKey?: string | null) {
  if (!serviceKey) {
    return null;
  }

  return serviceLogoSources[serviceKey] ?? null;
}
